services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - RATE_LIMIT_IP=20
      - BLOCK_DURATION_IP=15
      - RATE_LIMIT_PUBLIC=25
      - BLOCK_DURATION_PUBLIC=15
      - RATE_LIMIT_PREMIUM=30
      - BLOCK_DURATION_PREMIUM=10
      - RATE_LIMIT_ADMIN=40
      - BLOCK_DURATION_ADMIN=5
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
    networks:
      - rate-limiter-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - rate-limiter-network

volumes:
  redis-data:

networks:
  rate-limiter-network:
    driver: bridge
